import os
import glob
import re
import sys
import shutil
import threading
from flask import Flask, jsonify, send_from_directory, request

app = Flask(__name__, static_folder='static')
ARTICLES_DIR = os.path.expanduser('~/projects/homelab-intake/articles')
MOD_REGISTRY_FILE = os.path.expanduser('~/work/claude-code/modpipeline/data/registry.json')
SETTINGS_FILE = os.path.expanduser('~/projects/homelab-dashboard/settings.json')

# ModPipeline integration
from dotenv import load_dotenv
load_dotenv(os.path.expanduser('~/work/claude-code/modpipeline/.env'))

os.environ['MODPIPELINE_DATA_ROOT'] = os.path.expanduser('~/work/claude-code/modpipeline/data')
sys.path.insert(0, os.path.expanduser('~/work/claude-code/modpipeline'))
from common.paths import STAGING, APPROVED, REVIEW, DEPLOYED
from common.sidecar import read_json, write_reason
import registry as mod_registry
from deploy import pipeline as deploy_pipeline
from deploy.pipeline import DeployError

# Global path for media-curator to resolve imports for backend features
if '/home/linuxbox/projects/media-curator' not in sys.path:
    sys.path.append('/home/linuxbox/projects/media-curator')

_deploy_lock = threading.Lock()

# Strips AI-generated meta preambles like "This article discusses..." from summaries
SNIPPET_BOILERPLATE_RE = re.compile(
    r'^\s*(?:this|the)\s+(?:article|piece|post|report|guide|text|video|summary)\s+'
    r'(?:discusses|presents|introduces|explores|outlines|describes|covers|examines|explains|highlights|details|provides|offers)'
    r'\b[^.]*\.\s*',
    re.IGNORECASE
)

@app.route('/')
def index():
    return app.send_static_file('index.html')

@app.route('/api/articles')
def list_articles():
    if not os.path.exists(ARTICLES_DIR):
        return jsonify([])
    
    files = glob.glob(os.path.join(ARTICLES_DIR, '*.md'))
    # Sort files by name descending (which includes the timestamp)
    files.sort(reverse=True)
    
    articles = []
    for filepath in files:
        filename = os.path.basename(filepath)
        if filename.startswith('duplicate-'):
            continue
            
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
            title_match = re.search(r'^#\s+(.*)', content, re.MULTILINE)
            source_match = re.search(r'\*\*Source:\*\*\s+(.*)', content)
            date_match = re.search(r'\*\*Date:\*\*\s+(.*)', content)
            dup_match = re.search(r'\*\*Duplicate:\*\*\s+(True|False)', content)
            auto_match = re.search(r'\*\*AutoGenerated:\*\*\s+(True|False)', content)
            category_match = re.search(r'\*\*Category:\*\*\s+(.*)', content)
            tags_match = re.search(r'\*\*Tags:\*\*\s+(.*)', content)

            title = title_match.group(1) if title_match else filename.replace('.md', '')
            source = source_match.group(1) if source_match else ''
            date = date_match.group(1) if date_match else ''
            is_duplicate = dup_match.group(1) == 'True' if dup_match else False
            auto_generated = auto_match.group(1) == 'True' if auto_match else False
            category = category_match.group(1).strip() if category_match else ''
            tags = [t.strip() for t in tags_match.group(1).split(',') if t.strip()] if tags_match else []

            # Create a short snippet from the local summary, stripped of AI meta preambles
            summary_match = re.search(r'## Local AI Summary[^\n]*\n(.*?)(?:\n##(?!#)|$)', content, re.DOTALL)
            snippet = ''
            if summary_match:
                summary_text = SNIPPET_BOILERPLATE_RE.sub('', summary_match.group(1).strip()).strip()
                # Drop leading markdown heading lines (e.g. "### Key Concepts:") that read oddly as plain text
                summary_text = re.sub(r'^(?:#{1,6}[^\n]*\n+)+', '', summary_text).strip()
                snippet = summary_text[:150] + ('...' if len(summary_text) > 150 else '')

            articles.append({
                'id': filename,
                'title': title,
                'date': date,
                'source': source,
                'snippet': snippet,
                'is_duplicate': is_duplicate,
                'auto_generated': auto_generated,
                'category': category,
                'tags': tags,
                'raw_content': content.lower()
            })
            
    return jsonify(articles)

@app.route('/api/articles/<filename>')
def get_article(filename):
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return jsonify({'error': 'Not found'}), 404
        
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        
    return jsonify({'content': content})

@app.route('/api/articles/<filename>', methods=['DELETE'])
def delete_article(filename):
    filepath = os.path.join(ARTICLES_DIR, filename)
    if os.path.exists(filepath):
        os.remove(filepath)
        return jsonify({'success': True})
    return jsonify({'error': 'Not found'}), 404

@app.route('/api/articles/<filename>/duplicate', methods=['POST'])
def mark_duplicate(filename):
    filepath = os.path.join(ARTICLES_DIR, filename)
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        if '**Duplicate:**' in content:
            content = re.sub(r'\*\*Duplicate:\*\*\s+(True|False)', '**Duplicate:** True', content)
        else:
            content = content.replace('\n## Local AI Summary', '\n**Duplicate:** True\n\n## Local AI Summary', 1)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return jsonify({'success': True})
    return jsonify({'error': 'Not found'}), 404

@app.route('/api/articles/<filename>/resubmit', methods=['POST'])
def resubmit_article(filename):
    import json
    import uuid
    from datetime import datetime

    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return jsonify({'error': 'Not found'}), 404

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    source_match = re.search(r'\*\*Source:\*\*\s+(.*)', content)
    if not source_match:
        return jsonify({'error': 'No source URL found in article'}), 400
    url = source_match.group(1).strip()

    auto_match = re.search(r'\*\*AutoGenerated:\*\*\s+(True|False)', content)
    auto_generated = auto_match.group(1) == 'True' if auto_match else False

    QUEUE_FILE = os.path.expanduser('~/projects/homelab-intake/queue.json')
    q_list = []
    if os.path.exists(QUEUE_FILE):
        try:
            with open(QUEUE_FILE, 'r') as f:
                q_list = json.load(f)
        except Exception:
            q_list = []

    q_list.append({
        'id': str(uuid.uuid4()),
        'url': url,
        'status': 'pending',
        'auto_generated': auto_generated,
        'added_at': datetime.now().isoformat()
    })

    with open(QUEUE_FILE, 'w') as f:
        json.dump(q_list, f, indent=2)

    return jsonify({'success': True})

@app.route('/api/queue/<item_id>/retry', methods=['POST'])
def retry_queue_item(item_id):
    import json
    QUEUE_FILE = os.path.expanduser('~/projects/homelab-intake/queue.json')
    if not os.path.exists(QUEUE_FILE):
        return jsonify({'error': 'Queue not found'}), 404

    with open(QUEUE_FILE, 'r') as f:
        q_list = json.load(f)

    item = next((i for i in q_list if i['id'] == item_id), None)
    if not item:
        return jsonify({'error': 'Not found'}), 404

    item['status'] = 'pending'
    item['retry_count'] = 0
    item.pop('next_attempt_at', None)
    item.pop('last_error', None)
    item.pop('finished_at', None)

    with open(QUEUE_FILE, 'w') as f:
        json.dump(q_list, f, indent=2)

    return jsonify({'success': True})

@app.route('/api/queue')
def get_queue():
    import json
    QUEUE_FILE = os.path.expanduser('~/projects/homelab-intake/queue.json')
    if not os.path.exists(QUEUE_FILE):
        return jsonify([])
    try:
        with open(QUEUE_FILE, 'r') as f:
            return jsonify(json.load(f))
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/mods')
def get_mods():
    import json
    if not os.path.exists(MOD_REGISTRY_FILE):
        return jsonify({})
    try:
        with open(MOD_REGISTRY_FILE, 'r') as f:
            data = json.load(f)
        mods = data.get('mods', {})

        # Deployed submission dirs retain metadata.json (version) and
        # submission.json (submitted_at) even after deploy; registry.json
        # itself doesn't track version, so enrich by matching on sha256.
        deployed_by_hash = {}
        if DEPLOYED.exists():
            for d in DEPLOYED.iterdir():
                sub_path = d / "submission.json"
                meta_path = d / "metadata.json"
                if not sub_path.exists():
                    continue
                try:
                    sub_data = read_json(sub_path)
                except Exception:
                    continue
                version = None
                if meta_path.exists():
                    try:
                        version = read_json(meta_path).get('version')
                    except Exception:
                        pass
                deployed_by_hash[sub_data.get('sha256')] = {
                    'version': version,
                    'submitted_at': sub_data.get('arrived_at'),
                }

        for mod in mods.values():
            info = deployed_by_hash.get(mod.get('current_hash'))
            if info:
                mod['version'] = info['version']
                mod['submitted_at'] = info['submitted_at']

        return jsonify(mods)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/mods/staging')
def get_staging():
    submissions = []
    if STAGING.exists():
        for d in sorted(STAGING.iterdir()):
            meta_path = d / "metadata.json"
            sub_path = d / "submission.json"
            if meta_path.exists() and sub_path.exists():
                submissions.append({
                    "id": d.name,
                    "meta": read_json(meta_path),
                    "sub": read_json(sub_path)
                })
    return jsonify(submissions)

@app.route('/api/mods/approve/<sid>', methods=['POST'])
def approve_mod(sid):
    d = STAGING / sid
    if not d.exists():
        return jsonify({"error": "Not found"}), 404

    meta = read_json(d / "metadata.json")
    sub = read_json(d / "submission.json")
    decided_by = "parent"

    if not _deploy_lock.acquire(blocking=False):
        return jsonify({"error": "Deploy in progress"}), 409

    try:
        APPROVED.mkdir(parents=True, exist_ok=True)
        dest = APPROVED / d.name
        shutil.move(str(d), str(dest))
        mod_registry.record_submission(meta["mod_id"], sub["sha256"], sub["original_filename"],
                                       sub["submitted_by"], "approved_pending_deploy", decided_by=decided_by)
        deploy_pipeline.run(dest, meta, sub, decided_by=decided_by)
        DEPLOYED.mkdir(parents=True, exist_ok=True)
        final = DEPLOYED / dest.name
        shutil.move(str(dest), str(final))
        mod_registry.record_deployed(meta["mod_id"], sub["sha256"], sub["original_filename"],
                                     sub["submitted_by"], decided_by)
        return jsonify({"success": True, "message": f"{meta['name']} deployed."})
    except DeployError as exc:
        mod_registry.record_submission(meta["mod_id"], sub["sha256"], sub["original_filename"],
                                       sub["submitted_by"], "deploy_failed_rolled_back", decided_by=decided_by)
        return jsonify({"success": False, "error": str(exc)}), 500
    except Exception as exc:
        mod_registry.record_submission(meta["mod_id"], sub["sha256"], sub["original_filename"],
                                       sub["submitted_by"], "deploy_failed_error", decided_by=decided_by)
        return jsonify({"success": False, "error": f"Unexpected error: {str(exc)}"}), 500
    finally:
        _deploy_lock.release()

@app.route('/api/mods/reject/<sid>', methods=['POST'])
def reject_mod(sid):
    d = STAGING / sid
    if not d.exists():
        return jsonify({"error": "Not found"}), 404

    meta = read_json(d / "metadata.json")
    sub = read_json(d / "submission.json")
    data = request.json or {}
    reason = data.get("reason", "rejected via dashboard")
    decided_by = "parent"

    write_reason(d, "rejected_by_parent", reason)
    REVIEW.mkdir(parents=True, exist_ok=True)
    shutil.move(str(d), str(REVIEW / d.name))
    mod_registry.record_submission(meta["mod_id"], sub["sha256"], sub["original_filename"],
                                   sub["submitted_by"], "rejected", decided_by=decided_by)
    return jsonify({"success": True})

import sqlite3
import json

MEDIA_DB = os.path.expanduser('~/projects/media-curator/queue.db')

@app.route('/api/media/queue')
def get_media_queue():
    if not os.path.exists(MEDIA_DB):
        return jsonify([])
    import sys
    if '/home/linuxbox/projects/media-curator' not in sys.path:
        sys.path.append('/home/linuxbox/projects/media-curator')
    from database import get_conn
    conn = get_conn()
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    
    search = request.args.get('search', '')
    media_type = request.args.get('type', '')
    status = request.args.get('status', '')
    
    query = 'SELECT * FROM media_queue WHERE 1=1'
    params = []
    if search:
        query += ' AND (proposed_title LIKE ? OR original_filename LIKE ?)'
        params.extend([f'%{search}%', f'%{search}%'])
    if media_type:
        query += ' AND media_type = ?'
        params.append(media_type)
    if status:
        query += ' AND status = ?'
        params.append(status)
        
    query += ' ORDER BY created_at DESC LIMIT 100'
    c.execute(query, params)
    
    rows = []
    for r in c.fetchall():
        d = dict(r)
        d['metadata'] = json.loads(d['metadata_json']) if d['metadata_json'] else {}
        rows.append(d)
    conn.close()
    return jsonify(rows)

@app.route('/api/media/approve/<item_id>', methods=['POST'])
def approve_media(item_id):
    import sys
    if '/home/linuxbox/projects/media-curator' not in sys.path:
        sys.path.append('/home/linuxbox/projects/media-curator')
    try:
        from library import approve_item
        success, msg = approve_item(item_id)
        if success:
            return jsonify({'success': True})
        else:
            return jsonify({'error': msg}), 500
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/media/reclassify/<item_id>', methods=['POST'])
def reclassify_media(item_id):
    data = request.json
    new_type = data.get('media_type')
    
    import sys
    if '/home/linuxbox/projects/media-curator' not in sys.path:
        sys.path.append('/home/linuxbox/projects/media-curator')
    from database import get_conn
    conn = get_conn()
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute('SELECT * FROM media_queue WHERE id=?', (item_id,))
    row = c.fetchone()
    
    if not row:
        conn.close()
        return jsonify({'error': 'Not found'}), 404
        
    original_path = row['original_path']
    old_proposed = row['proposed_path']
    
    # If the file has already been moved to the library, use the library file as the source
    if row['status'] == 'approved' and old_proposed and os.path.exists(old_proposed):
        original_path = old_proposed
        c.execute('UPDATE media_queue SET original_path=? WHERE id=?', (original_path, item_id))
        # Do not unlink it! We will just move it.
    import sys
    if '/home/linuxbox/projects/media-curator' not in sys.path:
        sys.path.append('/home/linuxbox/projects/media-curator')
    try:
        from curator_daemon import identify_media
    except ImportError:
        conn.close()
        return jsonify({'error': 'Backend daemon not found.'}), 500
        
    is_group = False
    if os.path.isdir(original_path):
        is_group = True
        filename = os.path.basename(original_path)
        ext = ""
    else:
        filename = os.path.basename(original_path)
        ext = os.path.splitext(filename)[1].lower()

    res = identify_media(filename, original_path, ext, is_group=is_group, force_media_type=new_type)
    if not res:
        conn.close()
        return jsonify({'error': 'Failed to reclassify via backend daemon.'}), 500
        
    media_type, proposed_title, proposed_path, metadata, _ = res
    
    metadata['sort_logic'] = f"User manually reclassified as {new_type}."
    meta_str = json.dumps(metadata)
    
    c.execute('''UPDATE media_queue SET media_type=?, proposed_title=?, proposed_path=?, metadata_json=?, status="pending" WHERE id=?''',
              (new_type, proposed_title, proposed_path, meta_str, item_id))
    conn.commit()
    conn.close()
    
    # Re-approve automatically
    try:
        import sys
        if '/home/linuxbox/projects/media-curator' not in sys.path:
            sys.path.append('/home/linuxbox/projects/media-curator')
        from library import approve_item
        success, msg = approve_item(item_id)
        if not success:
            return jsonify({'error': msg}), 500
    except Exception as e:
        return jsonify({'error': str(e)}), 500
        
    return jsonify({'success': True})

@app.route('/api/media/reject/<item_id>', methods=['POST'])
def reject_media(item_id):
    import sys
    if '/home/linuxbox/projects/media-curator' not in sys.path:
        sys.path.append('/home/linuxbox/projects/media-curator')
    try:
        from library import reject_item
        success, msg = reject_item(item_id)
        if success:
            return jsonify({'success': True})
        else:
            return jsonify({'error': msg}), 500
    except Exception as e:
        return jsonify({'error': str(e)}), 500
    
@app.route('/api/media/edit/<item_id>', methods=['POST'])
def edit_media(item_id):
    data = request.json or {}
    import sqlite3
    from database import get_conn
    conn = get_conn()
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    
    if 'proposed_title' in data:
        new_title = data['proposed_title']
        c.execute('SELECT * FROM media_queue WHERE id=?', (item_id,))
        row = c.fetchone()
        if not row:
            conn.close()
            return jsonify({'error': 'Item not found'}), 404
            
        if row['status'] == 'approved':
            conn.close()
            return jsonify({'error': 'Cannot edit title of an approved item. Use Reclassify instead.'}), 400
            
        c.execute('UPDATE media_queue SET proposed_title=? WHERE id=?', (new_title, item_id))
        
    c.execute('UPDATE media_queue SET needs_intervention=0 WHERE id=?', (item_id,))
    conn.commit()
    conn.close()
    return jsonify({'success': True})

@app.route('/api/system/status')
def get_system_status():
    import subprocess
    import json
    import shutil
    
    status = {'defcon': [], 'containers': [], 'disk': {}, 'memory': {}}
    
    # 1. Check Disk Space on /mnt/Multimedia
    try:
        total, used, free = shutil.disk_usage('/mnt/Multimedia')
        free_pct = (free / total) * 100
        status['disk'] = {'total': total, 'used': used, 'free': free, 'free_pct': free_pct}
        if free_pct < 5.0:
            status['defcon'].append('STORAGE_CRITICAL: /mnt/Multimedia is below 5% free space!')
    except Exception:
        status['disk'] = {'error': 'Could not read /mnt/Multimedia'}

    # 2. Check Docker Containers & Plex Memory Limit
    try:
        docker_ps = subprocess.check_output(['docker', 'ps', '-a', '--format', '{{json .}}'], text=True)
        containers = [json.loads(line) for line in docker_ps.strip().split('\n') if line]
        status['containers'] = containers
        
        # Check VPN Killswitch Status
        gluetun = next((c for c in containers if 'gluetun' in c['Names']), None)
        if gluetun and ('unhealthy' in gluetun.get('Status', '').lower() or 'exited' in gluetun.get('Status', '').lower()):
            status['defcon'].append('VPN_DOWN: Gluetun tunnel has collapsed or failed authentication!')
            
        # Get memory stats for Plex (rough approximation using docker stats)
        # docker stats --no-stream --format "{{json .}}" plex
        try:
            plex_stats = subprocess.check_output(['docker', 'stats', '--no-stream', '--format', '{{json .}}', 'plex'], text=True)
            if plex_stats.strip():
                plex_data = json.loads(plex_stats.strip())
                status['memory']['plex'] = plex_data.get('MemUsage', 'Unknown')
        except:
            pass
            
    except Exception as e:
        status['containers'] = []

    # 3. Check Daemon Status
    try:
        daemon_status = subprocess.run(['systemctl', '--user', 'is-active', 'media-curator'], capture_output=True, text=True).stdout.strip()
        status['daemon_active'] = (daemon_status == 'active')
        if daemon_status != 'active':
            status['defcon'].append('DAEMON_CRASH: media-curator.service is not active!')
    except:
        status['daemon_active'] = False

    return jsonify(status)

@app.route("/setup")
def setup():
    DOWNLOADS_DIR = os.path.join(os.environ['MODPIPELINE_DATA_ROOT'], "downloads")
    return send_from_directory(DOWNLOADS_DIR, "automodpack-4.0.5.jar", as_attachment=True)

@app.route("/setup-loader-core")
def setup_loader_core():
    DOWNLOADS_DIR = os.path.join(os.environ['MODPIPELINE_DATA_ROOT'], "downloads")
    return send_from_directory(DOWNLOADS_DIR, "automodpack_mod-loader-fabric-core-4.0.5.jar", as_attachment=True)

@app.route("/downloads/<filename>")
def download(filename):
    DOWNLOADS_DIR = os.path.join(os.environ['MODPIPELINE_DATA_ROOT'], "downloads")
    return send_from_directory(DOWNLOADS_DIR, filename, as_attachment=True)

@app.route("/api/minecraft")
def get_minecraft_status():
    try:
        from mcstatus import JavaServer
        server = JavaServer.lookup("100.87.245.107:25565", timeout=1)
        status = server.status()
        return jsonify({
            'online': True,
            'players': status.players.online,
            'max_players': status.players.max,
            'version': status.version.name
        })
    except Exception as e:
        return jsonify({
            'online': False,
            'error': str(e)
        })

@app.route("/api/settings", methods=['GET'])
def get_settings():
    import json
    if not os.path.exists(SETTINGS_FILE):
        return jsonify({})
    try:
        with open(SETTINGS_FILE, 'r') as f:
            data = json.load(f)
            # Mask API keys
            for k in ['geminiApiKey', 'anthropicApiKey', 'openaiApiKey']:
                if k in data and data[k]:
                    data[k] = data[k][:8] + '*' * 20
            return jsonify(data)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route("/api/settings", methods=['POST'])
def save_settings():
    import json
    data = request.json or {}
    current = {}
    if os.path.exists(SETTINGS_FILE):
        try:
            with open(SETTINGS_FILE, 'r') as f:
                current = json.load(f)
        except: pass
        
    for k, v in data.items():
        if '*' not in str(v):  # Don't save masked keys back
            current[k] = v
            
    try:
        with open(SETTINGS_FILE, 'w') as f:
            json.dump(current, f, indent=2)
        return jsonify({'success': True})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/ai/chat', methods=['POST'])
def ai_chat():
    data = request.json or {}
    user_message = data.get('message', '')
    history_data = data.get('history', [])
    model = data.get('model', 'agy')

    if not user_message:
        return jsonify({'error': 'No message provided'}), 400

    # Load settings from file
    import json
    settings = {}
    if os.path.exists(SETTINGS_FILE):
        try:
            with open(SETTINGS_FILE, 'r') as f:
                settings = json.load(f)
        except: pass

    if model == 'local':
        # Example logic for local/Ollama using settings
        ollama_host = settings.get('ollamaHost', 'http://127.0.0.1:11434')
        return jsonify({'reply': f'The local model via {ollama_host} is currently offline or not fully configured.'})

    elif model == 'claude':
        # Anthropic integration
        import anthropic
        api_key = settings.get('anthropicApiKey') or os.environ.get('ANTHROPIC_API_KEY')
        if not api_key:
            return jsonify({'reply': 'Anthropic API key is not configured in Settings.'})
        
        try:
            client = anthropic.Anthropic(api_key=api_key)
            history_text = "\n".join([f"{m.get('role', 'user').title()}: {m.get('text', '')}" for m in history_data])
            prompt = f"{history_text}\n\nUser: {user_message}" if history_text else user_message
            
            message = client.messages.create(
                max_tokens=1024,
                messages=[
                    {"role": "user", "content": prompt}
                ],
                model="claude-sonnet-5",
            )
            return jsonify({'reply': message.content[0].text})
        except Exception as e:
            return jsonify({'reply': f'Error communicating with Claude: {str(e)}'}), 500

    elif model == 'agy':
        try:
            from google import genai
            from google.genai import types
            import os
            
            api_key = settings.get('geminiApiKey') or os.environ.get('GEMINI_API_KEY')
            if not api_key:
                return jsonify({'reply': 'GEMINI_API_KEY is not configured in Settings.'})

            # Define tools
            def get_minecraft_status_tool() -> str:
                """Returns the current online status and player count of the Minecraft server."""
                try:
                    from mcstatus import JavaServer
                    server = JavaServer.lookup("100.87.245.107:25565", timeout=2)
                    status = server.status()
                    return f"Minecraft server is Online. Players: {status.players.online}/{status.players.max}. Version: {status.version.name}"
                except Exception as e:
                    return f"Minecraft server is Offline or unreachable. Error: {str(e)}"

            def get_pending_mods_tool() -> str:
                """Returns a list of mods currently in the staging directory pending review."""
                try:
                    staging = []
                    if STAGING.exists():
                        for d in sorted(STAGING.iterdir()):
                            meta_path = d / "metadata.json"
                            sub_path = d / "submission.json"
                            if meta_path.exists() and sub_path.exists():
                                meta = read_json(meta_path)
                                staging.append(f"ID: {d.name}, Mod: {meta.get('name', 'Unknown')}")
                    if not staging:
                        return "No pending mods in staging."
                    return "\n".join(staging)
                except Exception as e:
                    return f"Error reading staging directory: {str(e)}"

            def approve_mod_tool(mod_id: str) -> str:
                """Approves a pending mod by its exact ID (e.g., '1234abcd') and deploys it."""
                # We can call the internal approve_mod logic, but we need to mock a request or just refactor.
                # Since the logic is coupled to Flask's request/jsonify, we can use test_client or refactor.
                # Simpler: just do the logic here for the tool.
                d = STAGING / mod_id
                if not d.exists():
                    return f"Error: Mod ID {mod_id} not found in staging."
                try:
                    meta = read_json(d / "metadata.json")
                    sub = read_json(d / "submission.json")
                    
                    if not _deploy_lock.acquire(blocking=False):
                        return "Error: A deployment is already in progress. Please try again later."
                        
                    try:
                        APPROVED.mkdir(parents=True, exist_ok=True)
                        dest = APPROVED / d.name
                        shutil.move(str(d), str(dest))
                        mod_registry.record_submission(meta["mod_id"], sub["sha256"], sub["original_filename"],
                                                       sub["submitted_by"], "approved_pending_deploy", decided_by="ai_assistant")
                        deploy_pipeline.run(dest, meta, sub, decided_by="ai_assistant")
                        DEPLOYED.mkdir(parents=True, exist_ok=True)
                        final = DEPLOYED / dest.name
                        shutil.move(str(dest), str(final))
                        mod_registry.record_deployed(meta["mod_id"], sub["sha256"], sub["original_filename"],
                                                     sub["submitted_by"], "ai_assistant")
                        return f"Success! Mod '{meta.get('name', mod_id)}' has been approved and deployed."
                    finally:
                        _deploy_lock.release()
                except Exception as e:
                    return f"Failed to approve mod: {str(e)}"

            def get_media_queue_tool() -> str:
                """Returns a list of media items currently in the queue pending approval."""
                try:
                    import sys
                    if '/home/linuxbox/projects/media-curator' not in sys.path:
                        sys.path.append('/home/linuxbox/projects/media-curator')
                    from database import get_conn
                    conn = get_conn()
                    conn.row_factory = sqlite3.Row
                    c = conn.cursor()
                    c.execute('SELECT id, original_filename, proposed_title, proposed_path, status FROM media_queue WHERE status="pending"')
                    items = c.fetchall()
                    conn.close()
                    if not items:
                        return "No pending media in queue."
                    res = []
                    for row in items:
                        res.append(f"ID: {row['id']} | File: {row['original_filename']} | Title: {row['proposed_title']} | Path: {row['proposed_path']}")
                    return "\n".join(res)
                except Exception as e:
                    return f"Error reading media queue: {str(e)}"
                    
            def approve_media_tool(item_id: str) -> str:
                """Approves a media item in the queue by its exact ID (e.g. '1234abcd')."""
                try:
                    import sys
                    if '/home/linuxbox/projects/media-curator' not in sys.path:
                        sys.path.append('/home/linuxbox/projects/media-curator')
                    from library import approve_item
                    success, msg = approve_item(item_id)
                    if success:
                        return f"Success! Media item '{item_id}' approved and moved to library."
                    else:
                        return f"Failed to approve media: {msg}"
                except Exception as e:
                    return f"Error: {str(e)}"
                    
            def reject_media_tool(item_id: str) -> str:
                """Rejects a media item in the queue by its exact ID."""
                try:
                    import sys
                    if '/home/linuxbox/projects/media-curator' not in sys.path:
                        sys.path.append('/home/linuxbox/projects/media-curator')
                    from library import reject_item
                    success, msg = reject_item(item_id)
                    if success:
                        return f"Success! Media item '{item_id}' rejected."
                    else:
                        return f"Failed to reject media: {msg}"
                except Exception as e:
                    return f"Error: {str(e)}"
                    
            def edit_media_tool(item_id: str, proposed_title: str = None) -> str:
                """Edits a media item's proposed title in the queue."""
                try:
                    import requests
                    payload = {}
                    if proposed_title: payload['proposed_title'] = proposed_title
                    resp = requests.post(f"http://127.0.0.1:8085/api/media/edit/{item_id}", json=payload)
                    if resp.status_code == 200:
                        return f"Success! Media item '{item_id}' updated."
                    else:
                        return f"Failed to edit media: {resp.text}"
                except Exception as e:
                    return f"Error: {str(e)}"

            dashboard_state = "You are an AI assistant built directly into the OmegaLab Dashboard sidebar. Be helpful, concise, and friendly. You have tools to manage the dashboard and server. When a user asks you to execute a change, first use a GET tool (like get_media_queue_tool) to find the ID of the item, then use the appropriate action tool (like edit_media_tool) with that ID."
            
            client = genai.Client(api_key=api_key)
            
            # Reconstruct history
            messages = []
            for msg in history_data:
                role = 'user' if msg.get('role') == 'user' else 'model'
                messages.append(types.Content(role=role, parts=[types.Part.from_text(text=msg.get('text', ''))]))
                
            messages.append(types.Content(role='user', parts=[types.Part.from_text(text=user_message)]))
            
            config = types.GenerateContentConfig(
                system_instruction=dashboard_state,
                tools=[get_minecraft_status_tool, get_pending_mods_tool, approve_mod_tool, get_media_queue_tool, approve_media_tool, reject_media_tool, edit_media_tool],
                temperature=0.5
            )
            
            # Let's handle tool calls manually because we need to return the final text to the frontend in one go
            # Wait, genai has automatic function calling if we use client.chats!
            chat = client.chats.create(model='gemini-2.5-flash', config=config)
            
            # Prime the chat history (excluding the very last user message)
            for msg in messages[:-1]:
                # Workaround: google-genai chat doesn't let us easily inject history yet via create().
                # We can just send the whole history as one text block if we want, or use generate_content
                pass
                
            # Actually, generate_content doesn't auto-call tools unless we use chat.
            # So we will just use chat.send_message, and format the history as context in the first message.
            history_text = "\n".join([f"{m.get('role', 'user').upper()}: {m.get('text', '')}" for m in history_data])
            if history_text:
                full_prompt = f"Previous conversation context:\n{history_text}\n\nUSER: {user_message}"
            else:
                full_prompt = user_message
                
            response = chat.send_message(full_prompt)
            return jsonify({'reply': response.text})
        except Exception as e:
            import traceback
            traceback.print_exc()
            return jsonify({'reply': f'Error communicating with Gemini: {str(e)}'}), 500

    return jsonify({'reply': f'Model {model} is not supported yet.'})



@app.route('/api/system/logs')
def system_logs():
    import os
    log_file = '/home/linuxbox/projects/media-curator/daemon.log'
    if not os.path.exists(log_file):
        return jsonify({'logs': []})
    try:
        with open(log_file, 'r') as f:
            lines = f.readlines()
            return jsonify({'logs': lines[-100:]}) # last 100 lines
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/media/upload', methods=['POST'])
def upload_media():
    import os
    from werkzeug.utils import secure_filename
    if 'file' not in request.files:
        return jsonify({'error': 'No file part'}), 400
    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No selected file'}), 400
    from curator_daemon import DROP_ZONE, is_contained
    os.makedirs(DROP_ZONE, exist_ok=True)
    filename = secure_filename(file.filename)
    if not filename:
        return jsonify({'error': 'Invalid filename'}), 400
    file_path = os.path.join(DROP_ZONE, filename)
    if not is_contained(file_path, DROP_ZONE):
        return jsonify({'error': 'Path traversal blocked'}), 400
    file.save(file_path)
    return jsonify({'success': True, 'filename': filename})

@app.route('/api/media/bulk_action', methods=['POST'])
def bulk_action():
    data = request.json or {}
    action = data.get('action')
    item_ids = data.get('item_ids', [])
    
    if not action or not item_ids:
        return jsonify({'error': 'Missing action or item_ids'}), 400
        
    results = []
    if action == 'approve':
        from library import approve_item
        for iid in item_ids:
            success, msg = approve_item(iid)
            results.append({'id': iid, 'success': success, 'msg': msg})
    elif action == 'reject':
        from library import reject_item
        for iid in item_ids:
            success, msg = reject_item(iid)
            results.append({'id': iid, 'success': success, 'msg': msg})
    else:
        return jsonify({'error': 'Invalid action'}), 400
        
    return jsonify({'results': results})

@app.route('/api/media/undo/<item_id>', methods=['POST'])
def undo_media(item_id):
    import os
    import shutil
    import sqlite3
    from database import get_conn
    conn = get_conn()
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute('SELECT * FROM media_queue WHERE id=?', (item_id,))
    row = c.fetchone()
    if not row or row['status'] != 'approved':
        conn.close()
        return jsonify({'error': 'Item not found or not approved'}), 400
        
    proposed_path = row['proposed_path']
    original_filename = row['original_filename']
    from curator_daemon import DROP_ZONE
    dest_path = os.path.join(DROP_ZONE, original_filename)
    
    if os.path.exists(proposed_path):
        if os.path.exists(dest_path):
            conn.close()
            return jsonify({'error': f'Destination {original_filename} already exists in drop zone.'}), 400
        try:
            shutil.move(proposed_path, dest_path)
        except Exception as e:
            conn.close()
            return jsonify({'error': f'Move failed: {str(e)}'}), 500
            
    c.execute('UPDATE media_queue SET status="pending", needs_intervention=1, original_path=? WHERE id=?', (dest_path, item_id))
    conn.commit()
    conn.close()
    return jsonify({'success': True})

@app.route('/api/media/cover/<item_id>')
def media_cover(item_id):
    import os
    import sqlite3
    from flask import send_file
    from database import get_conn
    conn = get_conn()
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute('SELECT * FROM media_queue WHERE id=?', (item_id,))
    row = c.fetchone()
    conn.close()
    
    if not row:
        return "Not found", 404
        
    search_path = row['proposed_path'] if row['status'] == 'approved' else row['original_path']
    if not search_path or not os.path.exists(search_path):
        return "No file", 404
        
    src_dir = os.path.dirname(search_path)
    cover_names = ['cover.jpg', 'cover.png', 'folder.jpg', 'poster.jpg']
    for name in cover_names:
        p = os.path.join(src_dir, name)
        if os.path.exists(p):
            return send_file(p)
            
    return "No cover found", 404

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8085, debug=False)
