import contextlib
import fcntl
import glob
import json
import math
import os
import re
import sqlite3
import tempfile
import uuid
from datetime import datetime

import requests
import yaml
from dotenv import dotenv_values

ARTICLES_DIR = os.path.expanduser('~/projects/homelab-intake/articles')
QUEUE_FILE = os.path.expanduser('~/projects/homelab-intake/queue.json')
QUEUE_LOCK_FILE = QUEUE_FILE + '.lock'
INDEX_DB = os.path.expanduser('~/projects/homelab-intake/index/articles.db')
INTAKE_CONFIG_FILE = os.path.expanduser('~/projects/homelab-intake/config.yaml')
INTAKE_ENV_FILE = os.path.expanduser('~/projects/homelab-intake/.env')

# Strips AI-generated meta preambles like "This article discusses..." from summaries
SNIPPET_BOILERPLATE_RE = re.compile(
    r'^\s*(?:this|the)\s+(?:article|piece|post|report|guide|text|video|summary)\s+'
    r'(?:discusses|presents|introduces|explores|outlines|describes|covers|examines|explains|highlights|details|provides|offers)'
    r'\b[^.]*\.\s*',
    re.IGNORECASE
)

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)


def _parse_frontmatter(content):
    """Returns (meta, body) or (None, None) if content isn't in the new YAML-frontmatter
    format. Kept as a lightweight inline parser (mirrors homelab-intake/intake/frontmatter.py)
    rather than a cross-repo import, since the dashboard already reads homelab-intake's files
    directly by path."""
    m = FRONTMATTER_RE.match(content)
    if not m:
        return None, None
    try:
        meta = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return None, None
    return meta, m.group(2)


def _full_summary_from_body(body, heading_pattern):
    summary_match = re.search(heading_pattern, body, re.DOTALL)
    if not summary_match:
        return ''
    summary_text = SNIPPET_BOILERPLATE_RE.sub('', summary_match.group(1).strip()).strip()
    return re.sub(r'^(?:#{1,6}[^\n]*\n+)+', '', summary_text).strip()


def _snippet_from_body(body, heading_pattern):
    summary_text = _full_summary_from_body(body, heading_pattern)
    return summary_text[:150] + ('...' if len(summary_text) > 150 else '')


def _reading_minutes(body: str) -> int:
    return max(1, round(len(body.split()) / 250))


def _article_from_frontmatter(filename, content, meta, body):
    tags = meta.get('tags') or []
    content_type = meta.get('content_type') or ''
    return {
        'id': filename,
        'title': meta.get('title') or filename.replace('.md', ''),
        'date': (meta.get('date_processed') or '')[:19].replace('T', ' '),
        'source': meta.get('source_url') or '',
        'snippet': _snippet_from_body(body, r'## Summary\n\n(.*?)(?:\n##(?!#)|$)'),
        'is_duplicate': bool(meta.get('dup_of')),
        'auto_generated': bool(meta.get('auto_generated')),
        'tags': [str(t) for t in tags],
        # Proposed by the pipeline but not yet in the vocabulary -- surfaced for one-click
        # approval rather than applied automatically (homelab-intake docs/DESIGN.md §5/§6).
        'suggested_tags': [str(t) for t in (meta.get('suggested_tags') or [])],
        'raw_content': content.lower(),
        'content_type': content_type,
        # The "save this to learn from later" axis (homelab-intake docs/DESIGN.md §5).
        # Absent on articles processed before the field shipped -- those read as False
        # until scripts/backfill_educational.py has run over the corpus.
        'educational': bool(meta.get('educational')),
        'priority_score': meta.get('priority_score'),
        'why_it_matters': meta.get('why_it_matters'),
        'user_folders': [str(f) for f in (meta.get('user_folders') or [])],
        'reading_minutes': _reading_minutes(body),
    }


def _article_from_legacy(filename, content):
    title_match = re.search(r'^#\s+(.*)', content, re.MULTILINE)
    source_match = re.search(r'\*\*Source:\*\*\s+(.*)', content)
    date_match = re.search(r'\*\*Date:\*\*\s+(.*)', content)
    dup_match = re.search(r'\*\*Duplicate:\*\*\s+(True|False)', content)
    auto_match = re.search(r'\*\*AutoGenerated:\*\*\s+(True|False)', content)
    tags_match = re.search(r'\*\*Tags:\*\*\s+(.*)', content)

    return {
        'id': filename,
        'title': title_match.group(1) if title_match else filename.replace('.md', ''),
        'date': date_match.group(1) if date_match else '',
        'source': source_match.group(1) if source_match else '',
        'snippet': _snippet_from_body(content, r'## Local AI Summary[^\n]*\n(.*?)(?:\n##(?!#)|$)'),
        'is_duplicate': dup_match.group(1) == 'True' if dup_match else False,
        'auto_generated': auto_match.group(1) == 'True' if auto_match else False,
        'tags': [t.strip() for t in tags_match.group(1).split(',') if t.strip()] if tags_match else [],
        'suggested_tags': [],
        'raw_content': content.lower(),
        'content_type': '',
        'educational': False,  # legacy articles predate the field entirely
        'priority_score': None,
        'why_it_matters': None,
        'user_folders': [],
        'reading_minutes': _reading_minutes(content),
    }


_articles_cache: dict = {'signature': None, 'articles': None}


def _articles_dir_signature() -> tuple:
    """Cheap (file, mtime) fingerprint of the articles directory -- a stat-only pass over
    ~85 files costs ~1ms vs. ~1.3s to actually parse them all, so list_articles() (called
    on every page load, by every tab's initial-load timer, and it only gets slower as the
    archive grows) can skip the full re-parse whenever nothing has actually changed."""
    files = glob.glob(os.path.join(ARTICLES_DIR, '*.md'))
    return tuple(sorted((f, os.path.getmtime(f)) for f in files))


# No `status`: homelab-intake retired it on 2026-09-11. Reading state (read/favorite/
# archived) is this repo's, in intake_state.json -- the index never carried it.
INDEX_COLUMNS = (
    'file_path, title, date_processed, source_url, dup_of, auto_generated, tags, '
    'suggested_tags, content_type, educational, priority_score, why_it_matters, '
    'user_folders, body, raw_content'
)


def _index_signature() -> tuple | None:
    try:
        st = os.stat(INDEX_DB)
    except OSError:
        return None
    return (st.st_mtime, st.st_size)


def _article_from_row(row) -> dict:
    """Build the same dict _article_from_frontmatter does, from an index row.

    The two must stay in step: this is the fast path and that one is the fallback for
    articles the index does not carry, and a page cannot tell which produced a given item."""
    (file_path, title, date_processed, source_url, dup_of, auto_generated, tags,
     suggested_tags, content_type, educational, priority_score, why_it_matters,
     user_folders, body, raw_content) = row
    filename = os.path.basename(file_path)
    body = body or ''
    return {
        'id': filename,
        'title': title or filename.replace('.md', ''),
        'date': (date_processed or '')[:19].replace('T', ' '),
        'source': source_url or '',
        'snippet': _snippet_from_body(body, r'## Summary\n\n(.*?)(?:\n##(?!#)|$)'),
        'is_duplicate': bool(dup_of),
        'auto_generated': bool(auto_generated),
        'tags': [str(t) for t in json.loads(tags or '[]')],
        'suggested_tags': [str(t) for t in json.loads(suggested_tags or '[]')],
        # Lowercased to match _article_from_frontmatter, because pages/intake.py:307
        # searches with `term in a['raw_content']` against an already-lowered term. The
        # index stores original case, so serving it raw made body search silently miss
        # every capitalised word -- for every article the index covers, which is all of
        # them. It still matched on title and tags, so it returned fewer results rather
        # than none, which is why nothing noticed.
        'raw_content': (raw_content or '').lower(),
        'content_type': content_type or '',
        'educational': bool(educational),
        'priority_score': priority_score,
        'why_it_matters': why_it_matters,
        'user_folders': [str(f) for f in json.loads(user_folders or '[]')],
        'reading_minutes': _reading_minutes(body),
    }


def _sync_index_row(filepath: str) -> None:
    """Push a frontmatter edit into the index row for that file.

    The dashboard rewrites frontmatter directly (tags, folders, dup_of) and the
    files stay canonical either way. But list_articles() now READS the index, so without
    this the list would keep serving the pre-edit row until the daemon happened to reindex
    -- the click would appear to do nothing. docs/DESIGN.md §7 already calls for exactly
    this: update SQLite immediately, patch the Markdown so files stay canonical.

    raw_content is refreshed too, not just the edited field: it is the whole file
    lowercased, so any frontmatter change alters what search matches.

    Never raises. The file is the source of truth; a stale index row is recoverable with a
    reindex, whereas an exception here would fail a save that already succeeded on disk."""
    try:
        if not os.path.exists(INDEX_DB) or not os.path.exists(filepath):
            return
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        meta, body = _parse_frontmatter(content)
        if meta is None:
            return
        conn = sqlite3.connect(INDEX_DB)
        try:
            conn.execute(
                """UPDATE articles SET title=?, content_type=?, tags=?, suggested_tags=?,
                       educational=?, why_it_matters=?, dup_of=?, user_folders=?,
                       body=?, raw_content=?
                   WHERE file_path=?""",
                (meta.get('title'), meta.get('content_type'),
                 json.dumps(meta.get('tags') or []),
                 json.dumps(meta.get('suggested_tags') or []),
                 1 if meta.get('educational') else 0,
                 meta.get('why_it_matters'),
                 meta.get('dup_of'),
                 json.dumps(meta.get('user_folders') or []),
                 body, content.lower(), filepath),
            )
            conn.commit()
        finally:
            conn.close()
    except (OSError, sqlite3.Error, ValueError):
        return


def _articles_from_index() -> tuple[list[dict], set[str]]:
    """Returns (articles, filenames the index covered). Empty on any index problem, so the
    file fallback below simply takes over rather than the page going blank."""
    if not os.path.exists(INDEX_DB):
        return [], set()
    try:
        conn = sqlite3.connect(f'file:{INDEX_DB}?mode=ro', uri=True)
        try:
            rows = conn.execute(f'SELECT {INDEX_COLUMNS} FROM articles').fetchall()
        finally:
            conn.close()
    except sqlite3.Error:
        return [], set()

    # Accept a row only when its file_path is inside the CURRENT ARTICLES_DIR. The index
    # describes one specific directory; if ARTICLES_DIR has been pointed elsewhere -- a test
    # fixture, a second corpus -- this index is not a cache of it, and serving its rows would
    # mix two unrelated corpora into one list.
    articles_dir = os.path.realpath(ARTICLES_DIR)
    articles, covered = [], set()
    for row in rows:
        if os.path.realpath(os.path.dirname(row[0])) != articles_dir:
            continue
        filename = os.path.basename(row[0])
        covered.add(filename)
        if filename.startswith('duplicate-'):
            continue
        articles.append(_article_from_row(row))
    return articles, covered


def list_articles() -> list[dict]:
    """Reads the SQLite index, not the article files -- homelab-intake's CLAUDE.md
    constraint 1, and a 257x difference in practice (1,579 ms to parse 119 files against
    6.1 ms to query them), which grows linearly with the archive.

    Files the index does not carry still fall back to parsing: articles predating the
    frontmatter migration, and any written since the last upsert. Today that set is empty,
    but a blank page would be a far worse failure than a slow one, so the fallback stays."""
    if not os.path.exists(ARTICLES_DIR):
        return []

    signature = (_index_signature(), _articles_dir_signature())
    if signature == _articles_cache['signature']:
        return _articles_cache['articles']

    articles, covered = _articles_from_index()

    for filepath in glob.glob(os.path.join(ARTICLES_DIR, '*.md')):
        filename = os.path.basename(filepath)
        if filename in covered or filename.startswith('duplicate-'):
            continue
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        meta, body = _parse_frontmatter(content)
        if meta is not None:
            articles.append(_article_from_frontmatter(filename, content, meta, body))
        else:
            articles.append(_article_from_legacy(filename, content))

    articles.sort(key=lambda a: a['id'], reverse=True)

    _articles_cache['signature'] = signature
    _articles_cache['articles'] = articles
    return articles


def get_article(filename: str) -> dict | None:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return None
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    meta, body = _parse_frontmatter(content)
    if meta is not None:
        summary = _full_summary_from_body(body, r'## Summary\n\n(.*?)(?:\n##(?!#)|$)')
        analysis = _full_summary_from_body(body, r'## Application Analysis\n+(.*?)(?:\n##(?!#)|$)')
        return {'content': body.strip(), 'summary': summary, 'analysis': analysis}
    summary = _full_summary_from_body(content, r'## Local AI Summary[^\n]*\n(.*?)(?:\n##(?!#)|$)')
    return {'content': content, 'summary': summary, 'analysis': ''}


def delete_article(filename: str) -> bool:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    os.remove(filepath)
    return True


def mark_duplicate(filename: str) -> bool:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    meta, body = _parse_frontmatter(content)
    if meta is not None:
        meta['dup_of'] = None if meta.get('dup_of') else 'manually flagged'
        yaml_block = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"---\n{yaml_block}---\n{body}")
        _sync_index_row(filepath)
        return True

    if '**Duplicate:**' in content:
        content = re.sub(r'\*\*Duplicate:\*\*\s+(True|False)', '**Duplicate:** True', content)
    else:
        content = content.replace('\n## Local AI Summary', '\n**Duplicate:** True\n\n## Local AI Summary', 1)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return True


def _mutate_user_folders(filename: str, mutate) -> bool:
    """Shared round-trip for add_to_folder/remove_from_folder: parse -> mutate meta's
    user_folders list -> yaml.safe_dump -> rewrite. Same pattern as mark_duplicate(). A
    no-op (returns False) for legacy-format articles -- custom folders are new
    functionality with no need to also patch the old bold-header format."""
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    meta, body = _parse_frontmatter(content)
    if meta is None:
        return False

    folders = [str(f) for f in (meta.get('user_folders') or [])]
    meta['user_folders'] = mutate(folders)
    yaml_block = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"---\n{yaml_block}---\n{body}")
    _sync_index_row(filepath)
    return True


TAGS_VOCAB_FILE = os.path.expanduser('~/projects/homelab-intake/tags_vocabulary.json')


def _normalise_tag(tag: str) -> str:
    """Must stay identical to homelab-intake's intake/tags.py normalise() -- both sides
    decide 'is this the same tag' and a divergence would re-fork OpenSource/open-source."""
    return re.sub(r'[\s\-_/.]+', '', tag.strip().lower())


def load_tag_vocabulary() -> list[str]:
    """The controlled vocabulary the pipeline reuses, in FILE ORDER -- which is descending
    corpus frequency (homelab-intake/scripts/seed_tag_vocabulary.py writes it that way, and
    the tagging prompt injects the top N by taking the first N). Callers wanting alphabetical
    display should sort their own copy rather than changing this."""
    if not os.path.exists(TAGS_VOCAB_FILE):
        return []
    try:
        with open(TAGS_VOCAB_FILE, 'r', encoding='utf-8') as f:
            return list(json.load(f))
    except (OSError, ValueError):
        return []


def promote_tag(tag: str) -> str:
    """Add a tag to the live vocabulary so the pipeline starts auto-applying it. Returns the
    spelling actually stored -- an existing normalised match wins over the passed spelling,
    which is what stops 'open source' re-entering next to 'OpenSource'."""
    tag = tag.strip()
    vocab = load_tag_vocabulary()
    existing = {_normalise_tag(t): t for t in vocab}
    key = _normalise_tag(tag)
    if key in existing:
        return existing[key]
    # Appended, and written back in order -- NOT re-sorted. The file's order is the frequency
    # ranking the tagging prompt reads, so sorting here would silently destroy it on the first
    # tag you accept in the UI. Appending is also correct on the merits: a tag being promoted
    # for the first time is the least-used one in the vocabulary.
    vocab.append(tag)
    tmp_fd, tmp_path = tempfile.mkstemp(dir=os.path.dirname(TAGS_VOCAB_FILE), suffix='.tmp')
    try:
        with os.fdopen(tmp_fd, 'w', encoding='utf-8') as f:
            json.dump(vocab, f, indent=2, ensure_ascii=False)
        os.replace(tmp_path, TAGS_VOCAB_FILE)
    except BaseException:
        with contextlib.suppress(OSError):
            os.unlink(tmp_path)
        raise
    return tag


def _mutate_tags(filename: str, mutate) -> bool:
    """Same round-trip as _mutate_user_folders, over the `tags` list. Also drops the tag from
    `suggested_tags` whenever it lands in `tags`, so an accepted suggestion stops being
    offered."""
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    meta, body = _parse_frontmatter(content)
    if meta is None:
        return False

    meta['tags'] = mutate([str(t) for t in (meta.get('tags') or [])])
    applied = {_normalise_tag(t) for t in meta['tags']}
    meta['suggested_tags'] = [
        str(t) for t in (meta.get('suggested_tags') or [])
        if _normalise_tag(str(t)) not in applied
    ]
    yaml_block = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"---\n{yaml_block}---\n{body}")
    _sync_index_row(filepath)
    return True


def add_tag(filename: str, tag: str) -> bool:
    """No cap on manual additions -- the 3-6 limit constrains the model, which is the source
    of vocabulary sprawl, not the human curating it."""
    tag = tag.strip()
    if not tag:
        return False
    key = _normalise_tag(tag)
    return _mutate_tags(
        filename,
        lambda tags: tags if any(_normalise_tag(t) == key for t in tags) else tags + [tag],
    )


def remove_tag(filename: str, tag: str) -> bool:
    key = _normalise_tag(tag)
    return _mutate_tags(filename, lambda tags: [t for t in tags if _normalise_tag(t) != key])


def dismiss_suggested_tag(filename: str, tag: str) -> bool:
    """Reject a suggestion without applying it."""
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    meta, body = _parse_frontmatter(content)
    if meta is None:
        return False
    key = _normalise_tag(tag)
    meta['suggested_tags'] = [
        str(t) for t in (meta.get('suggested_tags') or []) if _normalise_tag(str(t)) != key
    ]
    yaml_block = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"---\n{yaml_block}---\n{body}")
    _sync_index_row(filepath)
    return True


def add_to_folder(filename: str, folder: str) -> bool:
    return _mutate_user_folders(filename, lambda folders: folders if folder in folders else folders + [folder])


def remove_from_folder(filename: str, folder: str) -> bool:
    return _mutate_user_folders(filename, lambda folders: [f for f in folders if f != folder])


def resubmit_article(filename: str) -> dict:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return {'error': 'Not found'}

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    meta, _ = _parse_frontmatter(content)
    if meta is not None:
        url = meta.get('source_url')
        auto_generated = bool(meta.get('auto_generated'))
        if not url:
            return {'error': 'No source URL found in article'}
    else:
        source_match = re.search(r'\*\*Source:\*\*\s+(.*)', content)
        if not source_match:
            return {'error': 'No source URL found in article'}
        url = source_match.group(1).strip()
        auto_match = re.search(r'\*\*AutoGenerated:\*\*\s+(True|False)', content)
        auto_generated = auto_match.group(1) == 'True' if auto_match else False

    with _queue_lock():
        q_list = _read_queue()
        q_list.append({
            'id': str(uuid.uuid4()),
            'url': url,
            'status': 'pending',
            'auto_generated': auto_generated,
            'added_at': datetime.now().isoformat(),
        })
        _write_queue(q_list)
    return {'success': True}


def get_queue() -> list[dict]:
    return _read_queue()


def retry_queue_item(item_id: str) -> bool:
    with _queue_lock():
        q_list = _read_queue()
        item = next((i for i in q_list if i['id'] == item_id), None)
        if not item:
            return False

        item['status'] = 'pending'
        item['retry_count'] = 0
        item.pop('next_attempt_at', None)
        item.pop('last_error', None)
        item.pop('finished_at', None)

        _write_queue(q_list)
    return True


@contextlib.contextmanager
def _queue_lock():
    """Advisory lock guarding queue.json's read-modify-write cycle. fcntl.flock is
    stdlib and works across processes on the same host (not just threads in this
    process) -- needed because homelab-intake's intake_daemon.py, a separate
    long-running process, also reads and writes this same file (see
    homelab-intake/TODO.md -- that side still needs the matching lock)."""
    with open(QUEUE_LOCK_FILE, 'w') as lock_f:
        fcntl.flock(lock_f, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock_f, fcntl.LOCK_UN)


def _read_queue() -> list[dict]:
    if not os.path.exists(QUEUE_FILE):
        return []
    try:
        with open(QUEUE_FILE, 'r') as f:
            return json.load(f)
    except Exception:
        return []


def _write_queue(q_list: list[dict]) -> None:
    d = os.path.dirname(QUEUE_FILE)
    fd, tmp_path = tempfile.mkstemp(dir=d, prefix='.tmp-queue-', suffix='.json')
    try:
        with os.fdopen(fd, 'w') as f:
            json.dump(q_list, f, indent=2)
        os.replace(tmp_path, QUEUE_FILE)
    except Exception:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def _retrieve_similar_articles(question: str, top_k: int = 5) -> list[dict]:
    """Shared retrieval step behind search_articles() and search_articles_with_citations()
    -- reuses homelab-intake's existing embeddings index (index/articles.db) and
    nomic-embed-text model, mirroring homelab-intake/ask.py rather than importing it,
    same as the rest of this module reads homelab-intake's files directly by path
    instead of cross-repo importing."""
    if not os.path.exists(INDEX_DB):
        return []

    intake_env = dotenv_values(INTAKE_ENV_FILE)
    ollama_url = intake_env.get('OLLAMA_URL', 'http://127.0.0.1:11434')
    with open(INTAKE_CONFIG_FILE, 'r') as f:
        embedding_model = yaml.safe_load(f)['models']['embedding_model']

    resp = requests.post(
        f"{ollama_url}/api/embeddings",
        json={"model": embedding_model, "prompt": question[:8000]},
        timeout=30,
    )
    resp.raise_for_status()
    q_vec = resp.json()["embedding"]

    conn = sqlite3.connect(INDEX_DB)
    rows = conn.execute(
        "SELECT source_url, embedding FROM articles WHERE embedding IS NOT NULL"
    ).fetchall()

    scored = [
        (_cosine_similarity(q_vec, json.loads(embedding_json)), source_url)
        for source_url, embedding_json in rows
    ]
    scored.sort(reverse=True, key=lambda pair: pair[0])

    results = []
    for sim, source_url in scored[:top_k]:
        row = conn.execute(
            "SELECT file_path, title, tags, why_it_matters FROM articles WHERE source_url = ?",
            (source_url,),
        ).fetchone()
        if not row:
            continue
        file_path, title, tags_json, why_it_matters = row
        with open(file_path, 'r', encoding='utf-8') as article_file:
            content = article_file.read()
        _, body = _parse_frontmatter(content)
        results.append({
            'file_path': file_path, 'title': title, 'tags': tags_json,
            'why_it_matters': why_it_matters, 'source_url': source_url,
            'similarity': sim, 'body': body or '',
        })
    conn.close()
    return results


def search_articles(question: str, top_k: int = 5) -> str:
    """Semantic search over the archive -- plain-text result for the dashboard assistant."""
    if not os.path.exists(INDEX_DB):
        return "No article index found yet -- homelab-intake hasn't processed any articles."
    results = _retrieve_similar_articles(question, top_k)
    if not results:
        return "No matching articles found in the archive."
    blocks = [
        f"[{r['similarity']:.2f}] {r['title']}\nSource: {r['source_url']}\nTags: {r['tags']}\n"
        f"Why it matters: {r['why_it_matters']}\n\n{r['body'][:2000]}"
        for r in results
    ]
    return "\n\n---\n\n".join(blocks)


def search_articles_with_citations(question: str, top_k: int = 5) -> tuple[str, list[dict]]:
    """Same retrieval as search_articles(), but also returns citation records (article
    id + title) for AI Discuss's citation strips -- archive citations open the cited
    article in the reader rather than pointing at a file:line like repo citations do."""
    results = _retrieve_similar_articles(question, top_k)
    if not results:
        return "No matching articles found in the archive.", []
    blocks = []
    citations = []
    for r in results:
        blocks.append(f"[{r['similarity']:.2f}] {r['title']}\n\n{r['body'][:1500]}")
        citations.append({'article_id': os.path.basename(r['file_path']), 'title': r['title'], 'kind': 'archive'})
    return "\n\n---\n\n".join(blocks), citations
