import contextlib
import fcntl
import glob
import json
import math
import os
import re
import sqlite3
import tempfile
import uuid
from datetime import datetime

import requests
import yaml
from dotenv import dotenv_values

ARTICLES_DIR = os.path.expanduser('~/projects/homelab-intake/articles')
QUEUE_FILE = os.path.expanduser('~/projects/homelab-intake/queue.json')
QUEUE_LOCK_FILE = QUEUE_FILE + '.lock'
INDEX_DB = os.path.expanduser('~/projects/homelab-intake/index/articles.db')
INTAKE_CONFIG_FILE = os.path.expanduser('~/projects/homelab-intake/config.yaml')
INTAKE_ENV_FILE = os.path.expanduser('~/projects/homelab-intake/.env')

# Strips AI-generated meta preambles like "This article discusses..." from summaries
SNIPPET_BOILERPLATE_RE = re.compile(
    r'^\s*(?:this|the)\s+(?:article|piece|post|report|guide|text|video|summary)\s+'
    r'(?:discusses|presents|introduces|explores|outlines|describes|covers|examines|explains|highlights|details|provides|offers)'
    r'\b[^.]*\.\s*',
    re.IGNORECASE
)

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)


def _parse_frontmatter(content):
    """Returns (meta, body) or (None, None) if content isn't in the new YAML-frontmatter
    format. Kept as a lightweight inline parser (mirrors homelab-intake/intake/frontmatter.py)
    rather than a cross-repo import, since the dashboard already reads homelab-intake's files
    directly by path."""
    m = FRONTMATTER_RE.match(content)
    if not m:
        return None, None
    try:
        meta = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return None, None
    return meta, m.group(2)


def _full_summary_from_body(body, heading_pattern):
    summary_match = re.search(heading_pattern, body, re.DOTALL)
    if not summary_match:
        return ''
    summary_text = SNIPPET_BOILERPLATE_RE.sub('', summary_match.group(1).strip()).strip()
    return re.sub(r'^(?:#{1,6}[^\n]*\n+)+', '', summary_text).strip()


def _snippet_from_body(body, heading_pattern):
    summary_text = _full_summary_from_body(body, heading_pattern)
    return summary_text[:150] + ('...' if len(summary_text) > 150 else '')


def _reading_minutes(body: str) -> int:
    return max(1, round(len(body.split()) / 250))


def _article_from_frontmatter(filename, content, meta, body):
    tags = meta.get('tags') or []
    content_type = meta.get('content_type') or ''
    primary_domain = meta.get('primary_domain') or ''
    # Preserves the existing two-folder Homelab/News split (pages/intake.py) on top of the
    # new orthogonal schema until the dashboard itself is rebuilt (docs/BUILD_BACKLOG.md
    # Milestone C, Design-first — not done here).
    category = 'Homelab' if primary_domain == 'homelab' else 'News'
    return {
        'id': filename,
        'title': meta.get('title') or filename.replace('.md', ''),
        'date': (meta.get('date_processed') or '')[:19].replace('T', ' '),
        'source': meta.get('source_url') or '',
        'snippet': _snippet_from_body(body, r'## Summary\n\n(.*?)(?:\n##(?!#)|$)'),
        'is_duplicate': bool(meta.get('dup_of')),
        'auto_generated': bool(meta.get('auto_generated')),
        'category': category,
        'tags': [str(t) for t in tags],
        'raw_content': content.lower(),
        # New fields, unused by the current UI but available for when it's rebuilt.
        'content_type': content_type,
        'primary_domain': primary_domain,
        # The "save this to learn from later" axis (homelab-intake docs/DESIGN.md §5).
        # Absent on articles processed before the field shipped -- those read as False
        # until scripts/backfill_educational.py has run over the corpus.
        'educational': bool(meta.get('educational')),
        'priority_score': meta.get('priority_score'),
        'why_it_matters': meta.get('why_it_matters'),
        'status': meta.get('status') or 'Inbox',
        'user_folders': [str(f) for f in (meta.get('user_folders') or [])],
        'reading_minutes': _reading_minutes(body),
    }


def _article_from_legacy(filename, content):
    title_match = re.search(r'^#\s+(.*)', content, re.MULTILINE)
    source_match = re.search(r'\*\*Source:\*\*\s+(.*)', content)
    date_match = re.search(r'\*\*Date:\*\*\s+(.*)', content)
    dup_match = re.search(r'\*\*Duplicate:\*\*\s+(True|False)', content)
    auto_match = re.search(r'\*\*AutoGenerated:\*\*\s+(True|False)', content)
    category_match = re.search(r'\*\*Category:\*\*\s+(.*)', content)
    tags_match = re.search(r'\*\*Tags:\*\*\s+(.*)', content)

    return {
        'id': filename,
        'title': title_match.group(1) if title_match else filename.replace('.md', ''),
        'date': date_match.group(1) if date_match else '',
        'source': source_match.group(1) if source_match else '',
        'snippet': _snippet_from_body(content, r'## Local AI Summary[^\n]*\n(.*?)(?:\n##(?!#)|$)'),
        'is_duplicate': dup_match.group(1) == 'True' if dup_match else False,
        'auto_generated': auto_match.group(1) == 'True' if auto_match else False,
        'category': category_match.group(1).strip() if category_match else '',
        'tags': [t.strip() for t in tags_match.group(1).split(',') if t.strip()] if tags_match else [],
        'raw_content': content.lower(),
        'content_type': '',
        'primary_domain': '',
        'educational': False,  # legacy articles predate the field entirely
        'priority_score': None,
        'why_it_matters': None,
        'status': 'Inbox',
        'user_folders': [],
        'reading_minutes': _reading_minutes(content),
    }


_articles_cache: dict = {'signature': None, 'articles': None}


def _articles_dir_signature() -> tuple:
    """Cheap (file, mtime) fingerprint of the articles directory -- a stat-only pass over
    ~85 files costs ~1ms vs. ~1.3s to actually parse them all, so list_articles() (called
    on every page load, by every tab's initial-load timer, and it only gets slower as the
    archive grows) can skip the full re-parse whenever nothing has actually changed."""
    files = glob.glob(os.path.join(ARTICLES_DIR, '*.md'))
    return tuple(sorted((f, os.path.getmtime(f)) for f in files))


def list_articles() -> list[dict]:
    if not os.path.exists(ARTICLES_DIR):
        return []

    signature = _articles_dir_signature()
    if signature == _articles_cache['signature']:
        return _articles_cache['articles']

    files = glob.glob(os.path.join(ARTICLES_DIR, '*.md'))
    files.sort(reverse=True)

    articles = []
    for filepath in files:
        filename = os.path.basename(filepath)
        if filename.startswith('duplicate-'):
            continue

        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        meta, body = _parse_frontmatter(content)
        if meta is not None:
            articles.append(_article_from_frontmatter(filename, content, meta, body))
        else:
            articles.append(_article_from_legacy(filename, content))

    _articles_cache['signature'] = signature
    _articles_cache['articles'] = articles
    return articles


def get_article(filename: str) -> dict | None:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return None
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    meta, body = _parse_frontmatter(content)
    if meta is not None:
        summary = _full_summary_from_body(body, r'## Summary\n\n(.*?)(?:\n##(?!#)|$)')
        analysis = _full_summary_from_body(body, r'## Application Analysis\n+(.*?)(?:\n##(?!#)|$)')
        return {'content': body.strip(), 'summary': summary, 'analysis': analysis}
    summary = _full_summary_from_body(content, r'## Local AI Summary[^\n]*\n(.*?)(?:\n##(?!#)|$)')
    return {'content': content, 'summary': summary, 'analysis': ''}


def delete_article(filename: str) -> bool:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    os.remove(filepath)
    return True


def mark_duplicate(filename: str) -> bool:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    meta, body = _parse_frontmatter(content)
    if meta is not None:
        meta['dup_of'] = None if meta.get('dup_of') else 'manually flagged'
        yaml_block = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"---\n{yaml_block}---\n{body}")
        return True

    if '**Duplicate:**' in content:
        content = re.sub(r'\*\*Duplicate:\*\*\s+(True|False)', '**Duplicate:** True', content)
    else:
        content = content.replace('\n## Local AI Summary', '\n**Duplicate:** True\n\n## Local AI Summary', 1)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    return True


def _mutate_user_folders(filename: str, mutate) -> bool:
    """Shared round-trip for add_to_folder/remove_from_folder: parse -> mutate meta's
    user_folders list -> yaml.safe_dump -> rewrite. Same pattern as mark_duplicate(). A
    no-op (returns False) for legacy-format articles -- custom folders are new
    functionality with no need to also patch the old bold-header format."""
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return False
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    meta, body = _parse_frontmatter(content)
    if meta is None:
        return False

    folders = [str(f) for f in (meta.get('user_folders') or [])]
    meta['user_folders'] = mutate(folders)
    yaml_block = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"---\n{yaml_block}---\n{body}")
    return True


def add_to_folder(filename: str, folder: str) -> bool:
    return _mutate_user_folders(filename, lambda folders: folders if folder in folders else folders + [folder])


def remove_from_folder(filename: str, folder: str) -> bool:
    return _mutate_user_folders(filename, lambda folders: [f for f in folders if f != folder])


def resubmit_article(filename: str) -> dict:
    filepath = os.path.join(ARTICLES_DIR, filename)
    if not os.path.exists(filepath):
        return {'error': 'Not found'}

    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    meta, _ = _parse_frontmatter(content)
    if meta is not None:
        url = meta.get('source_url')
        auto_generated = bool(meta.get('auto_generated'))
        if not url:
            return {'error': 'No source URL found in article'}
    else:
        source_match = re.search(r'\*\*Source:\*\*\s+(.*)', content)
        if not source_match:
            return {'error': 'No source URL found in article'}
        url = source_match.group(1).strip()
        auto_match = re.search(r'\*\*AutoGenerated:\*\*\s+(True|False)', content)
        auto_generated = auto_match.group(1) == 'True' if auto_match else False

    with _queue_lock():
        q_list = _read_queue()
        q_list.append({
            'id': str(uuid.uuid4()),
            'url': url,
            'status': 'pending',
            'auto_generated': auto_generated,
            'added_at': datetime.now().isoformat(),
        })
        _write_queue(q_list)
    return {'success': True}


def get_queue() -> list[dict]:
    return _read_queue()


def retry_queue_item(item_id: str) -> bool:
    with _queue_lock():
        q_list = _read_queue()
        item = next((i for i in q_list if i['id'] == item_id), None)
        if not item:
            return False

        item['status'] = 'pending'
        item['retry_count'] = 0
        item.pop('next_attempt_at', None)
        item.pop('last_error', None)
        item.pop('finished_at', None)

        _write_queue(q_list)
    return True


@contextlib.contextmanager
def _queue_lock():
    """Advisory lock guarding queue.json's read-modify-write cycle. fcntl.flock is
    stdlib and works across processes on the same host (not just threads in this
    process) -- needed because homelab-intake's intake_daemon.py, a separate
    long-running process, also reads and writes this same file (see
    homelab-intake/TODO.md -- that side still needs the matching lock)."""
    with open(QUEUE_LOCK_FILE, 'w') as lock_f:
        fcntl.flock(lock_f, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock_f, fcntl.LOCK_UN)


def _read_queue() -> list[dict]:
    if not os.path.exists(QUEUE_FILE):
        return []
    try:
        with open(QUEUE_FILE, 'r') as f:
            return json.load(f)
    except Exception:
        return []


def _write_queue(q_list: list[dict]) -> None:
    d = os.path.dirname(QUEUE_FILE)
    fd, tmp_path = tempfile.mkstemp(dir=d, prefix='.tmp-queue-', suffix='.json')
    try:
        with os.fdopen(fd, 'w') as f:
            json.dump(q_list, f, indent=2)
        os.replace(tmp_path, QUEUE_FILE)
    except Exception:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    norm_a = math.sqrt(sum(x * x for x in a))
    norm_b = math.sqrt(sum(y * y for y in b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def _retrieve_similar_articles(question: str, top_k: int = 5) -> list[dict]:
    """Shared retrieval step behind search_articles() and search_articles_with_citations()
    -- reuses homelab-intake's existing embeddings index (index/articles.db) and
    nomic-embed-text model, mirroring homelab-intake/ask.py rather than importing it,
    same as the rest of this module reads homelab-intake's files directly by path
    instead of cross-repo importing."""
    if not os.path.exists(INDEX_DB):
        return []

    intake_env = dotenv_values(INTAKE_ENV_FILE)
    ollama_url = intake_env.get('OLLAMA_URL', 'http://127.0.0.1:11434')
    with open(INTAKE_CONFIG_FILE, 'r') as f:
        embedding_model = yaml.safe_load(f)['models']['embedding_model']

    resp = requests.post(
        f"{ollama_url}/api/embeddings",
        json={"model": embedding_model, "prompt": question[:8000]},
        timeout=30,
    )
    resp.raise_for_status()
    q_vec = resp.json()["embedding"]

    conn = sqlite3.connect(INDEX_DB)
    rows = conn.execute(
        "SELECT source_url, embedding FROM articles WHERE embedding IS NOT NULL"
    ).fetchall()

    scored = [
        (_cosine_similarity(q_vec, json.loads(embedding_json)), source_url)
        for source_url, embedding_json in rows
    ]
    scored.sort(reverse=True, key=lambda pair: pair[0])

    results = []
    for sim, source_url in scored[:top_k]:
        row = conn.execute(
            "SELECT file_path, title, tags, why_it_matters FROM articles WHERE source_url = ?",
            (source_url,),
        ).fetchone()
        if not row:
            continue
        file_path, title, tags_json, why_it_matters = row
        with open(file_path, 'r', encoding='utf-8') as article_file:
            content = article_file.read()
        _, body = _parse_frontmatter(content)
        results.append({
            'file_path': file_path, 'title': title, 'tags': tags_json,
            'why_it_matters': why_it_matters, 'source_url': source_url,
            'similarity': sim, 'body': body or '',
        })
    conn.close()
    return results


def search_articles(question: str, top_k: int = 5) -> str:
    """Semantic search over the archive -- plain-text result for the dashboard assistant."""
    if not os.path.exists(INDEX_DB):
        return "No article index found yet -- homelab-intake hasn't processed any articles."
    results = _retrieve_similar_articles(question, top_k)
    if not results:
        return "No matching articles found in the archive."
    blocks = [
        f"[{r['similarity']:.2f}] {r['title']}\nSource: {r['source_url']}\nTags: {r['tags']}\n"
        f"Why it matters: {r['why_it_matters']}\n\n{r['body'][:2000]}"
        for r in results
    ]
    return "\n\n---\n\n".join(blocks)


def search_articles_with_citations(question: str, top_k: int = 5) -> tuple[str, list[dict]]:
    """Same retrieval as search_articles(), but also returns citation records (article
    id + title) for AI Discuss's citation strips -- archive citations open the cited
    article in the reader rather than pointing at a file:line like repo citations do."""
    results = _retrieve_similar_articles(question, top_k)
    if not results:
        return "No matching articles found in the archive.", []
    blocks = []
    citations = []
    for r in results:
        blocks.append(f"[{r['similarity']:.2f}] {r['title']}\n\n{r['body'][:1500]}")
        citations.append({'article_id': os.path.basename(r['file_path']), 'title': r['title'], 'kind': 'archive'})
    return "\n\n---\n\n".join(blocks), citations
